### ISSUE TITLE
Привет! Срочный вопрос по актуальности данных

### ISSUE THREAD

**Issue by ivanstnsk** [Adushar/UkraineCitiesAndVillages#1]
Хай
Отписался на доу, не знаю заметишь ли.
На странице контактов не вижу поэтому создаю ишую)

Есть вопрос насколько актуальны данные по городам и откуда бралась инфа?

**Comment by Adushar** [comment]
Привіт. Використовув данні з КОАТУУ, вони актуальні на зараз. Як виявилося в цьому реєстрі є проблема з великими містами, тому рекомендував тобі б використовувати КАТОТТГ. Якщо зможеш згенерити таку ж JSON і XML я можу оновити

**Comment by ivanstnsk** [comment]
Понял спасибо! Как раз тоже нашел что нужно использовать КАТОТТГ т.к. это актуально после ликвидации районов. Попробую сгенерить новый json

**Comment by ivanstnsk** [comment]
Тема себя исчерпала
